/aruco_node:
  ros__parameters:
    marker_size: 0.0625
    aruco_dictionary_id: DICT_5X5_250 #DICT_5X5_250
    image_topic: /image_raw #/image_raw
    camera_info_topic: /camera_info
    camera_frame: rear_camera_color_optical_frame
